name: Deploy to HubSpot

on:
  push:
    branches:
      - master # Cambiado de main a master basándose en el repositorio actual

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to HubSpot
        uses: HubSpot/hubspot-cms-deploy-action@v2.1.0
        with:
          account_id: ${{ secrets.HUBSPOT_PORTAL_ID }}
          personal_access_key: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
          src_dir: "."
          dest_dir: "'Carlosguisan Showcase'"
