name: Deploy to HubSpot

on:
  push:
    branches:
      - master # Cambiado de main a master basándose en el repositorio actual

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli@latest
      - name: Deploy to HubSpot
        env:
          HUBSPOT_ACCESS_TOKEN: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
          HUBSPOT_PORTAL_ID: ${{ secrets.HUBSPOT_PORTAL_ID }}
        run: |
          hs cms upload . "Carlosguisan Showcase" --portal=$HUBSPOT_PORTAL_ID --token=$HUBSPOT_ACCESS_TOKEN
